[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1028:Enum Storage should be Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1031:Do not catch general exception types")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1032:Implement standard exception constructors")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1034:Nested types should not be visible")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1051:Do not declare visible instance fields")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1062:Validate arguments of public methods", Scope = "member", Target = "~M:Jannesen.Protocol.SMTP.SMTPBadReplyException.#ctor(Jannesen.Protocol.SMTP.SMTPConnection,System.String,Jannesen.Protocol.SMTP.SMTPResponse)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming",        "CA1707:Identifiers should not contain underscores")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance",   "CA1819:Properties should not return arrays")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability",   "CA2007:Consider calling ConfigureAwait on the awaited task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style",         "IDE0028:Simplify collection initialization")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style",         "IDE1006:Naming Styles")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality",  "IDE0067:Dispose objects before losing scope", Scope = "member", Target = "~M:Jannesen.Protocol.SMTP.SMTPConnection.DATA(System.Byte[],System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability",   "CA2000:Dispose objects before losing scope",  Scope = "member", Target = "~M:Jannesen.Protocol.SMTP.SMTPConnection.DATA(System.Byte[],System.Int32)")]
